version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80
    restart: always
    links:
      - db